# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usb_storage"
    "sd_mod"
    "rtsx_usb_sdmmc"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];
  boot.supportedFilesystems = [
    "btrfs"
    "ext4"
    "ntfs"
  ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1d2f1e9e-57cd-4a1f-8205-9ca0aa95fac6";
    fsType = "btrfs";
    options = [ "subvol=@" ];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/B56E-0176";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/fa8e7f11-004a-49a0-8eb6-f4c9545f7973";
    fsType = "btrfs";
    options = [
      # Access times are not written to drive at all
      # https://wiki.archlinux.org/title/Fstab#atime_options
      "noatime"
    ];
  };

  fileSystems."/mnt/d" = {
    device = "/dev/disk/by-uuid/D854B2BA54B29B28";
    fsType = "ntfs";
    options = [
      "rw"
      "big_writes"
      "noatime"
      "uid=petr"
      "gid=users"
    ];
  };

  fileSystems."/mnt/f" = {
    device = "/dev/disk/by-uuid/20F6D631F6D606C6";
    fsType = "ntfs";
    options = [
      "rw"
      "big_writes"
      "noatime"
      "uid=petr"
      "gid=users"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/0472e23c-62d3-412a-909d-2947ec11e76f"; }
  ];

  zramSwap.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
