# https://clangd.llvm.org/config.html

CompileFlags:
  Add: [
    -Wall,
    -pedantic,
    # -std=c++23,
    # -std=c23,
  ]

Index:
  StandardLibrary: Yes

#   https://clangd.llvm.org/config#inlayhints
InlayHints:
  BlockEnd: Yes
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24

Diagnostics:
  ClangTidy:
    Add: [
      modernize*,
      readability*,
      performance*,
      misc*,
      cppcoreguidelines*,
      bugprone*,
    ]
    Remove: [
      bugprone-easily-swappable-parameters,
      cppcoreguidelines-avoid-non-const-global-variables,
      readability-identifier-length,
      readability-math-missing-parentheses,
    ]

