# https://clangd.llvm.org/config.html

CompileFlags:
  Add: [
    -xc++,
    -Wall,
    -pedantic,
    --std=gnu++20,
  ]

Index:
  StandardLibrary: Yes

Diagnostics:
  ClangTidy:
    Add: [
      modernize*,
      readability*,
      performance*,
      misc*,
      cppcoreguidelines*,
      bugprone*,
    ]
    Remove: [
      bugprone-easily-swappable-parameters,
      cppcoreguidelines-avoid-non-const-global-variables,
      readability-identifier-length,
    ]

